import { BrandLogo } from '@/components/brand-logo';

/**
 * Layout for the signed-out routes.
 *
 * ## The composition decision
 *
 * A centred card on an empty page is the reflex layout for an auth screen and
 * it proves nothing — it could belong to any product. This is a split instead:
 * the left half states what the product does and shows a **real draft it
 * produced**, the right half is the form.
 *
 * That left half is the honest version of a marketing panel. Rather than a
 * feature list, it shows the artifact itself, because the only thing worth
 * proving on a sign-up screen is that the output is good.
 *
 * On mobile the split collapses and the panel moves *below* the form. The form
 * is the job; the pitch should not be what a phone user has to scroll past.
 *
 * @param props - Standard layout props.
 * @param props.children - The active auth route.
 * @returns The auth shell.
 * @sideeffect none
 */
export default function AuthLayout({ children }: { children: React.ReactNode }) {
  return (
    <div className="grid min-h-dvh lg:grid-cols-[1.1fr_1fr]">
      {/* The form half. `order` puts it first on mobile, second on desktop. */}
      <main className="order-1 flex flex-col justify-center px-6 py-12 lg:order-2 lg:px-16">
        <div className="mx-auto flex w-full max-w-sm flex-col gap-8">
          <div className="flex items-center gap-2 lg:hidden">
            <BrandLogo className="size-8" priority />
            <span className="text-lg font-semibold tracking-tight">BrandLoop</span>
          </div>
          {children}
        </div>
      </main>

      {/*
        The panel. Hidden below `lg` rather than shrunk, because a compressed
        version of a two-column composition reads as clutter rather than as a
        deliberate layout.
      */}
      <aside className="bg-muted/40 border-border order-2 hidden flex-col justify-between border-r px-16 py-14 lg:order-1 lg:flex">
        <div className="flex items-center gap-2.5">
          <BrandLogo className="size-10" priority />
          <span className="text-lg font-semibold tracking-tight">BrandLoop</span>
        </div>

        <div className="flex max-w-md flex-col gap-8">
          <p className="text-2xl leading-snug font-medium tracking-tight text-balance">
            Your expertise, turned into posts that sound like you wrote them on a good day.
          </p>

          {/*
            Real output from this system, not a mockup. The niche and the
            author's own points were the only inputs — everything here was
            generated by the same pipeline the dashboard drives.
          */}
          <figure className="border-border bg-card rounded-lg border p-5">
            <figcaption className="text-muted-foreground mb-3 flex items-center gap-2 font-mono text-xs tracking-wide uppercase">
              <span className="bg-status-approved size-1.5 rounded-full" aria-hidden="true" />
              Generated draft · X
            </figcaption>
            <blockquote className="prose-draft text-[0.9375rem]">
              Clinicians will ignore a perfect AI risk score if the interface hides the evidence. I
              spent 3 years deploying AI in NHS trusts. Accuracy means nothing without context. Map
              the specific lab values and patient history or watch doctors ignore the tool.
            </blockquote>
            <p className="text-muted-foreground mt-3 text-xs">276 of 280 characters</p>
          </figure>

          <p className="text-muted-foreground text-sm leading-relaxed">
            Set your niche and what you actually think. BrandLoop plans a week or a month, drafts
            every post for X and LinkedIn, and sends each one to Discord for you to approve.
          </p>
        </div>

        <p className="text-muted-foreground text-xs">
          Posts are drafted for you and approved by you. Nothing publishes on its own.
        </p>
      </aside>
    </div>
  );
}
